### PR TITLE
Fix bookmark icon on hover

### LINKED ISSUE #32: Bookmark icons not showing on hovering over the thumbnails
**Describe the bug**
When we hover over the image, the bookmark icons are not showing. In place of it, `bookmark_border` and `bookmark` text is displayed.

This bug is a result of Pull https://github.com/creativecommons/ccsearch-browser-extension/pull/29 . We have moved from material icons to font awesome icons. The syntax of describing the icon is different in both of them.

_Material icons_: 
`<i class="material-icons" id="bookmark">bookmarks</i>`

_Font Awesome icon_:
`<i class="fa fa-bookmark" id="bookmark"></i>`

This bug is a result of this difference.

The code in question can be found [here](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/searchModule.js#L181)  and [here](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/bookmarkModule.js#L173)

**To Reproduce**
1. Open the extension and search for something.
2. Hover over the thumbnail.
3. Also, bookmark some image and hover over them in the bookmarks section.

**Expected behavior**
We should see the bookmark [this](https://fontawesome.com/v4.7.0/icon/bookmark-o) icon instead of text `bookmark_border` and [this](https://fontawesome.com/v4.7.0/icon/bookmark) icon instead of `bookmark` text on hovering over the images.

Also, the size and the position of the icons should also be adjusted if needed.

**Screenshots**
<br>

_Current_

Screenshot (207)

<br>

_Target_

search-images-attribution (1)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by bennetthanna**
Fixes #32

**Description**
Fix the bookmark icon so that it uses the the correct Font Awesome icon syntax. On hover, in the search module it displays the bookmark outline icon. On hover in the bookmark module it displays the filled in bookmark icon.

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

File: src/popup/bookmarkModule.js [hunk 1]
```diff
@@ -16,7 +16,6 @@ export default function bookmarkImage(e) {
     if (bookmarksArray.indexOf(e.target.dataset.imageid) === -1) {
       bookmarksArray.push(e.target.dataset.imageid);
       chrome.storage.sync.set({ bookmarks: bookmarksArray }, () => {
-        e.target.innerText = 'bookmark';
```
Comment (makkoncept) [inline src/popup/bookmarkModule.js]: This statement was used to confirm and provide feedback to the user that the bookmark has been registered by changing the bookmark icon from [bordered](https://material.io/resources/icons/?icon=bookmark_border&style=baseline) to [filled](https://material.io/resources/icons/?icon=bookmark&style=baseline).
Instead of deleting, it should be modified to do the same thing with font awesome icons

**Review by makkoncept — CHANGES_REQUESTED** [review]
Hi @bennetthanna, The changes are working fine locally.
I have added a comment requesting a change. We can merge the PR after that!

File: src/popup/bookmarkModule.js (hunk 1 above)
Comment (bennetthanna) [reply src/popup/bookmarkModule.js]: @makkoncept I changed it so that it displayed the filled bookmark icon when the image has been bookmarked.

It was also doing a thing where if you left the search module and then went back to it with the same search query, the icon was not displaying the filled in icon even though it had been previously bookmarked. I changed that in [this commit](https://github.com/creativecommons/ccsearch-browser-extension/pull/35/commits/5ce0f60aa7f6d7c3c6cd1f2f0bba6b5353fc44cc). It looks like a big change but the only things that changed were I [pulled the bookmarks from storage](https://github.com/creativecommons/ccsearch-browser-extension/pull/35/commits/5ce0f60aa7f6d7c3c6cd1f2f0bba6b5353fc44cc#diff-ac6db3f8e57ca4502560c69f517a9030R104-R105) and then [checked if that image has been bookmarked or not](https://github.com/creativecommons/ccsearch-browser-extension/pull/35/commits/5ce0f60aa7f6d7c3c6cd1f2f0bba6b5353fc44cc#diff-ac6db3f8e57ca4502560c69f517a9030R179-R191) and conditionally render outlined or filled.

Let me know what you think!

**Review by makkoncept — APPROVED** [review]
